version: "3"
includes:
  accounts:
    taskfile: ./diamonbank-accounts/Taskfile.yml
    dir: ./diamonbank-accounts
  cards:
    taskfile: ./diamonbank-cards/Taskfile.yml
    dir: ./diamonbank-cards
  loans:
      taskfile: ./diamonbank-loans/Taskfile.yml
      dir: ./diamonbank-loans
  config-server:
    taskfile: ./diamonbank-config-server/Taskfile.yml
    dir: ./diamonbank-config-server
  eureka-server:
    taskfile: ./diamonbank-eureka-server/Taskfile.yml
    dir: ./diamonbank-eureka-server
  apigateway:
    taskfile: ./diamoncode-apigateway/Taskfile.yml
    dir: ./diamoncode-apigateway
  web:
    taskfile: ./diamonbank-web/Taskfile.yml
    dir: ./diamonbank-web

tasks:
  docker-pull-images:
    dotenv: ['docker/.env_template']
    cmds:
      - docker pull $CONFIG_SERVER_IMAGE
      - docker pull $EUREKA_SERVER_IMAGE
      - docker pull $ACCOUNTS_IMAGE
      - docker pull $LOANS_IMAGE
      - docker pull $CARDS_IMAGE
      - docker pull $I18N_IMAGE
      - docker pull $APIGATEWAY_IMAGE
      - echo 'All images were downloaded!'
    silent: true
  docker-compose-up:
    cmds:
      - cd docker && docker compose up -d
    silent: true
  docker-compose-up-debug:
    cmds:      
      - cd docker && docker compose -f docker-compose.yml -f docker-compose-debug.yml up -d
    silent: true
  docker-compose-stop:
    cmds:
      - cd docker && docker compose stop
    silent: true
  docker-compose-down:
    cmds:
      - cd docker && docker compose down
    silent: true

  
