version: "3"

vars:
  IMAGE_NAME: diamonbank-accounts
  LOCAL_IMAGE: local/{{.IMAGE_NAME}}:SNAPSHOT
  DOCKER_HUB_IMAGE_VERSION: chamow01/{{.IMAGE_NAME}}:v2

tasks:
  mvn-clean-install:
    cmds:
      - mvn clean install -Dmaven.test.skip=true
  local-image:
    cmds:
      - task: mvn-clean-install
      - docker build -t {{.LOCAL_IMAGE}} .
  docker-hub-image:
    cmds:
      - task: mvn-clean-install
      - docker build -t {{.DOCKER_HUB_IMAGE_VERSION}} .
      - docker push {{.DOCKER_HUB_IMAGE_VERSION}}
