server:
  port: 8072
config:
  api-name: "dc-api"
  endpoints:
    ACCOUNTS: "accounts"
    CUSTOMERS: "customer"
    LOANS: "loans"
    CARDS: "cards"
spring:
  application:
    name: "gatewayserver"

  #########################################################
  #Properties for security
  #########################################################
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/wladecodeusers
          jwk-set-uri: http://localhost:7080/realms/wladecodeusers/protocol/openid-connect/certs

  #########################################################
  #Properties for configserver
  #########################################################
  config:
    import: optional:configserver:http://localhost:8071/
  #########################################################
  #Configuration gateway
  #########################################################
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
        #enabled: true
        #lower-case-service-id: true
      routes:
        # CONFIG POR ACCOUNTS MS
        - id: accounts-ms
          uri: lb://accounts
          predicates:
            - Path=/${config.api-name}/${config.endpoints.ACCOUNTS}/actuator/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.ACCOUNTS}/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: accounts-ms
          uri: lb://accounts
          predicates:
            - Path=/${config.api-name}/${config.endpoints.ACCOUNTS}/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.ACCOUNTS}/(?<segment>.*), /accounts/$\{segment}
            - name: AddResponseHeaders
              args:
                headers: "CALCULO,MATE"
                withHeaders: true
        - id: accounts-ms-customers
          uri: lb://accounts
          predicates:
            - Path=/${config.api-name}/${config.endpoints.CUSTOMERS}/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.CUSTOMERS}/(?<segment>.*), /customer/$\{segment}
        # CONFIG POR LOANS MS
        - id: loans-ms
          uri: lb://loans
          predicates:
            - Path=/${config.api-name}/${config.endpoints.LOANS}/actuator/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.LOANS}/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: loans-ms
          uri: lb://loans
          predicates:
            - Path=/${config.api-name}/${config.endpoints.LOANS}/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.LOANS}/(?<segment>.*), /loans/$\{segment}
            - AddResponseHeaders

        # CONFIG POR CARDS
        - id: cards-ms
          uri: lb://cards
          predicates:
            - Path=/${config.api-name}/${config.endpoints.CARDS}/actuator/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.CARDS}/actuator/(?<segment>.*), /actuator/$\{segment}
        - id: cads-ms
          uri: lb://cards
          predicates:
            - Path=/${config.api-name}/${config.endpoints.CARDS}/**
          filters:
            - RewritePath=/${config.api-name}/${config.endpoints.CARDS}/(?<segment>.*), /cards/$\{segment}
  #USED BY LOG AGREGATION WITH ZIPKIN
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411/

#########################################################
#Actuator endpoint
#FOr all endpoints management.endpoints.web.exposure.include=*
#########################################################
management:
  # Enables actuator/gateway
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "health, info, gateway, prometheus"
  # Enables actuator/info
  info:
    env:
      enabled: true

#########################################################
#Configuration info
#########################################################
info:
  application:
    name: '@project.name@'
    description: '@project.description@'
    version: '@project.version@'

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.diamoncode.diamonbankapigateway: DEBUG



#########################################################
#Eureka client configuration
#########################################################
eureka:
  instance:
    instance-id: '${spring.application.name}:${random.uuid}:${server.port}'
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


