encrypt:
  key-store:
    alias: config-server-key
    location: security/config-server.jks
    password: st0res3cr3t1cs
    secret: d14monb4nk-20dos
server:
  port: 8071
spring:
  application:
    name: configserver
  profiles:
    active: composite
  cloud:
    config:
      server:
        composite:
          - type: native
            uri: file://config
            order: 1
          - type: git
            uri: https://github.com/chamoW/diamonbank-microservices-config.git
            clone-on-start: true
            default-label: master
            force-pull: true
            order: 2
            # uri: https://github.com/giancarlolm/service-configuration

  rabbitmq:
    host: localhost
    password: password
    port: 5672
    username: username
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://localhost:9411/
    rabbitmq:
      queue: from-zipkin
    sender:
      type: rabbit
